services:
  app:
    build: .
    container_name: weather_app
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=weather_db;User=root;Password=changeme;
    ports:
      - "8080:8080"
      - "52971:52971"

  mysql:
    image: mysql:latest
    container_name: weather_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: weather_db
    ports:
      - "3309:3309"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./WeatherThreading.Server/WeatherData.sql:/docker-entrypoint-initdb.d/WeatherData.sql

volumes:
  mysql_data:
