services:
  app:
    build: .
    container_name: weather_app
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=weather_db;User=root;Password=changeme;Port=3306;
    ports:
      - "8080:8080"
      - "52971:52971"
    restart: on-failure:5

  mysql:
    image: mysql:latest
    container_name: weather_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: weather_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 2s
      timeout: 3s
      retries: 30
      start_period: 10s

volumes:
  mysql_data: